spring:
  profiles:
    active: development
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB

  jpa:
    show-sql: true
  h2:
    console:
      enabled: true

admin:
  username: sxxxi
  password: foobar

keys:
  location:
    privateKey: ./src/main/resources/keys/private.der
    publicKey: ./src/main/resources/keys/public.der